spring:
  datasource:
    url: jdbc:mysql://1.15.32.65:3306/demo_security?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**

  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/java
        - src/main/resources
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
